# Generated by Django 4.2.5 on 2023-09-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eixos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_eixo', models.CharField(max_length=200)),
                ('cidade', models.CharField(choices=[('Ariqumes', 'Ariquemes'), ('Porto Velho', 'Porto Velho'), ('Alto Alegre', 'Alto Alegre'), ('Buritis', 'Buritis'), ('Cerejeiras', 'Cerejeiras'), ('Pimenta Bueno', 'Pimenta Bueno')], max_length=200)),
                ('coordenador_eixo', models.CharField(max_length=200)),
                ('objetivo_eixo', models.TextField()),
            ],
        ),
    ]
