# Generated by Django 4.2.5 on 2023-09-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eixos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eixos',
            name='cidade',
            field=models.CharField(choices=[('Ariquemes', 'Ariquemes'), ('Porto Velho', 'Porto Velho'), ('Alto Alegre', 'Alto Alegre'), ('Buritis', 'Buritis'), ('Cerejeiras', 'Cerejeiras'), ('Pimenta Bueno', 'Pimenta Bueno')], max_length=200),
        ),
    ]
