# Generated by Django 4.2.5 on 2023-09-28 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_alter_relatorio_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='comprovante_pagamento',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes_pagamento/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Comprovante de Pag.'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='situacao',
            field=models.CharField(choices=[('pago', 'pago'), ('recusado', 'recusado'), ('aguardando', 'aguardando')], default='aguardando', max_length=15),
        ),
    ]
