# Generated by Django 4.2.5 on 2023-09-28 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0003_relatorio_comprovante_pagamento_relatorio_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='comprovante_pagamento',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes_pagamento/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Comprovante de Pag. - Reservado para o setor Financeiro'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='situacao',
            field=models.CharField(choices=[('pago', 'pago'), ('recusado', 'recusado'), ('aguardando', 'aguardando')], default='aguardando', max_length=15, verbose_name='Situacão'),
        ),
    ]
