# Generated by Django 4.2.5 on 2023-09-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='carga_horaria',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
