# Generated by Django 4.2.5 on 2023-09-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsistas', '0002_alter_bolsista_carga_horaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolsista',
            name='tipo_bolsa',
            field=models.CharField(choices=[('Bolsista Superior', 'Bolsista Superior'), ('Bolsista Médio', 'Bolsista Médio')], max_length=50),
        ),
    ]
